<?php

declare(strict_types=1);

namespace StubbeDev\LaravelStoli\Generation;

use StubbeDev\LaravelStoli\Utils;

/**
 * A file Stoli generates. It always starts with self::HEADER, which is how a file an
 * earlier run left behind is told apart from one written by hand.
 */
final readonly class GeneratedFile
{
    public const HEADER = '// Generated by stoli:generate - do not edit.';

    public string $path;

    public string $contents;

    /**
     * @param  string  $path  resolved against the application root unless it is absolute
     * @param  bool  $format  whether the typescript-transformer formatter runs over it
     */
    public function __construct(string $path, string $contents, public bool $format = true)
    {
        $this->path = Utils::absolutePath($path);
        $this->contents = self::HEADER."\n\n".ltrim($contents);
    }

    /**
     * Whether $contents is what Stoli generated, or a version before the header did: a
     * file starting with $legacy.
     */
    public static function isGenerated(string $contents, ?string $legacy = null): bool
    {
        return str_starts_with($contents, self::HEADER) || ($legacy !== null && str_starts_with($contents, $legacy));
    }
}
