<?php

declare(strict_types=1);

namespace StubbeDev\LaravelStoli\Compilers;

use BackedEnum;
use JsonSerializable;
use StubbeDev\LaravelStoli\Items\ConstantGroup;
use UnitEnum;

/**
 * Compiles discovered constant groups into a single TypeScript file.
 *
 * The PHP namespace is mirrored as nested plain objects, so a constant on
 * App\Support\Permission is reachable as App.Support.Permission.VIEW, and each
 * group also gets a union type of its values:
 *
 *     export const App = {
 *         Support: {
 *             Permission: {
 *                 VIEW: 'view',
 *             },
 *         },
 *     } as const;
 *
 *     export type Permission = (typeof App.Support.Permission)[keyof typeof App.Support.Permission];
 *
 * Constants holding a value with no TypeScript equivalent (an object that is
 * neither an enum case nor JsonSerializable, a resource, a closure) are left out.
 */
final readonly class ConstantsFileCompiler
{
    private const IDENTIFIER = '/^[A-Za-z_$][A-Za-z0-9_$]*$/';

    public function extension(): string
    {
        return 'ts';
    }

    /**
     * @param  list<ConstantGroup>  $groups
     */
    public function compile(array $groups): string
    {
        $groups = $this->renderable($groups);

        if ($groups === []) {
            return '';
        }

        $tree = $this->tree($groups);

        $blocks = [];

        foreach ($tree as $name => $node) {
            $blocks[] = "export const {$name} = ".$this->renderNode($node, 0).' as const;';
        }

        $aliases = $this->typeAliases($groups, array_keys($tree));

        $body = implode("\n\n", [...$blocks, ...$aliases]);

        return <<<TS
        // Generated by stoli:generate - do not edit.

        {$body}

        TS;
    }

    /**
     * Drop the constants that have no TypeScript representation, and with them
     * any group left without a single constant.
     *
     * @param  list<ConstantGroup>  $groups
     * @return list<ConstantGroup>
     */
    private function renderable(array $groups): array
    {
        $kept = [];

        foreach ($groups as $group) {
            $constants = array_filter(
                $group->constants(),
                fn (mixed $value): bool => $this->renderValue($value, 0) !== null
            );

            if ($constants === []) {
                continue;
            }

            $kept[] = new ConstantGroup(
                className: $group->className(),
                namespace: $group->namespace(),
                name: $group->name(),
                constants: $constants,
            );
        }

        return $kept;
    }

    /**
     * Nest the groups by their namespace segments. Branches are arrays, leaves
     * are the groups themselves.
     *
     * A group whose path is already taken — a class sharing its name with a
     * namespace, or two classes published under the same path — is skipped
     * rather than silently overwriting the one that got there first.
     *
     * @param  list<ConstantGroup>  $groups
     * @return array<string, mixed>
     */
    private function tree(array $groups): array
    {
        $tree = [];

        foreach ($groups as $group) {
            $segments = $group->segments();
            $leaf = array_pop($segments);

            $node = &$tree;
            $reachable = true;

            foreach ($segments as $segment) {
                if (! isset($node[$segment])) {
                    $node[$segment] = [];
                }

                if (! is_array($node[$segment])) {
                    $reachable = false;

                    break;
                }

                $node = &$node[$segment];
            }

            if ($reachable && ! isset($node[$leaf])) {
                $node[$leaf] = $group;
            }

            unset($node);
        }

        return $tree;
    }

    private function renderNode(array|ConstantGroup $node, int $depth): string
    {
        $entries = $node instanceof ConstantGroup
            ? array_map(
                fn (mixed $value): string => $this->renderValue($value, $depth + 1) ?? 'undefined',
                $node->constants()
            )
            : array_map(
                fn (array|ConstantGroup $child): string => $this->renderNode($child, $depth + 1),
                $node
            );

        return $this->object($entries, $depth);
    }

    /**
     * @param  array<string, string>  $entries  already rendered values, keyed by property name
     */
    private function object(array $entries, int $depth): string
    {
        if ($entries === []) {
            return '{}';
        }

        $inner = str_repeat("\t", $depth + 1);
        $lines = [];

        foreach ($entries as $key => $value) {
            $lines[] = $inner.$this->key((string) $key).': '.$value.',';
        }

        return "{\n".implode("\n", $lines)."\n".str_repeat("\t", $depth).'}';
    }

    private function key(string $key): string
    {
        return preg_match(self::IDENTIFIER, $key) === 1 ? $key : $this->string($key);
    }

    /**
     * Render a PHP value as TypeScript, or null when it has no representation.
     */
    private function renderValue(mixed $value, int $depth): ?string
    {
        if ($value === null) {
            return 'null';
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_int($value)) {
            return (string) $value;
        }

        if (is_float($value)) {
            return is_finite($value) ? var_export($value, true) : null;
        }

        if (is_string($value)) {
            return $this->string($value);
        }

        if ($value instanceof BackedEnum) {
            return $this->renderValue($value->value, $depth);
        }

        if ($value instanceof UnitEnum) {
            return $this->string($value->name);
        }

        if ($value instanceof JsonSerializable) {
            $serialized = $value->jsonSerialize();

            return $serialized instanceof JsonSerializable
                ? null
                : $this->renderValue($serialized, $depth);
        }

        if (is_array($value)) {
            return $this->renderArray($value, $depth);
        }

        return null;
    }

    private function renderArray(array $value, int $depth): ?string
    {
        $rendered = [];

        foreach ($value as $key => $item) {
            $itemValue = $this->renderValue($item, $depth + 1);

            if ($itemValue === null) {
                return null;
            }

            $rendered[$key] = $itemValue;
        }

        if ($rendered === []) {
            return array_is_list($value) ? '[]' : '{}';
        }

        if (! array_is_list($value)) {
            return $this->object($rendered, $depth);
        }

        $inner = str_repeat("\t", $depth + 1);
        $lines = array_map(static fn (string $item): string => $inner.$item.',', $rendered);

        return "[\n".implode("\n", $lines)."\n".str_repeat("\t", $depth).']';
    }

    private function string(string $value): string
    {
        $escaped = str_replace(
            ['\\', "'", "\n", "\r", "\t"],
            ['\\\\', "\\'", '\n', '\r', '\t'],
            $value
        );

        return "'{$escaped}'";
    }

    /**
     * One exported union type per group, named after the group. Names that would
     * collide — with another group or with a top-level constant object — take in
     * enclosing namespace segments until they are unique.
     *
     * @param  list<ConstantGroup>  $groups
     * @param  list<string>  $reserved
     * @return list<string>
     */
    private function typeAliases(array $groups, array $reserved): array
    {
        $taken = array_flip($reserved);
        $aliases = [];

        foreach ($groups as $group) {
            $name = $this->uniqueTypeName($group, $taken);
            $taken[$name] = true;
            $path = $group->path();

            $aliases[] = "export type {$name} = (typeof {$path})[keyof typeof {$path}];";
        }

        return $aliases;
    }

    /**
     * @param  array<string, mixed>  $taken
     */
    private function uniqueTypeName(ConstantGroup $group, array $taken): string
    {
        $segments = $group->segments();
        $name = (string) array_pop($segments);

        while (isset($taken[$name]) && $segments !== []) {
            $name = array_pop($segments).$name;
        }

        $candidate = $name;
        $suffix = 2;

        while (isset($taken[$candidate])) {
            $candidate = $name.$suffix++;
        }

        return $candidate;
    }
}
