<?php

declare(strict_types=1);

namespace StubbeDev\LaravelStoli\Compilers;

use BackedEnum;
use JsonSerializable;
use StubbeDev\LaravelStoli\Items\ConstantGroup;
use UnitEnum;

/**
 * Compiles discovered constant groups into a single TypeScript file.
 *
 * The PHP namespace is mirrored as nested plain objects, so a constant on
 * App\Support\Permission is reachable as App.Support.Permission.VIEW, and each
 * group also gets a union type of its values:
 *
 *     export const App = {
 *         Support: {
 *             Permission: {
 *                 VIEW: 'view',
 *             },
 *         },
 *     } as const;
 *
 *     export type Permission = (typeof App.Support.Permission)[keyof typeof App.Support.Permission];
 *
 * Constants holding a value with no TypeScript equivalent (an object that is
 * neither an enum case nor JsonSerializable, a resource, a closure) are left out.

 */
final readonly class ConstantsFileCompiler
{
    /**
     * The first line of every file this compiler writes, which is how a file left
     * behind by an earlier run is told apart from one written by hand.
     */
    public const HEADER = '// Generated by stoli:generate - do not edit.';

    /**
     * @param  list<ConstantGroup>  $groups
     */
    public function compile(array $groups): string
    {
        [$tree, $placed] = $this->tree($this->renderable($groups));

        if ($placed === []) {
            return '';
        }

        $blocks = [];

        foreach ($tree as $name => $node) {
            $blocks[] = "export const {$name} = ".$this->renderNode($node, 0).' as const;';
        }

        $body = implode("\n\n", [...$blocks, ...$this->typeAliases($placed, array_map(strval(...), array_keys($tree)))]);

        $header = self::HEADER;

        return <<<TS
        {$header}

        {$body}

        TS;
    }

    /**
     * Drop the constants that have no TypeScript representation, and with them
     * any group left without a single constant.
     *
     * @param  list<ConstantGroup>  $groups
     * @return list<ConstantGroup>
     */
    private function renderable(array $groups): array
    {
        $kept = [];

        foreach ($groups as $group) {
            $constants = array_filter(
                $group->constants(),
                fn (mixed $value): bool => $this->renderValue($value, 0) !== null
            );

            if ($constants === []) {
                continue;
            }

            $kept[] = new ConstantGroup(
                className: $group->className(),
                namespace: $group->namespace(),
                name: $group->name(),
                constants: $constants,
            );
        }

        return $kept;
    }

    /**
     * Nest the groups by their namespace segments. Branches are arrays, leaves
     * are the groups themselves.
     *
     * A group whose path is already taken — a class sharing its name with a
     * namespace, or two classes published under the same path — is skipped
     * rather than silently overwriting the one that got there first, and is
     * left out of the returned list so it gets no type alias either.
     *
     * @param  list<ConstantGroup>  $groups
     * @return array{array<mixed>, list<ConstantGroup>} the tree and the groups placed in it
     */
    private function tree(array $groups): array
    {
        $tree = [];
        $placed = [];

        foreach ($groups as $group) {
            if (self::place($tree, $group->namespace(), $group)) {
                $placed[] = $group;
            }
        }

        return [$tree, $placed];
    }

    /**
     * @param  array<mixed>  $node
     * @param  list<string>  $segments  the namespace segments left to descend
     */
    private static function place(array &$node, array $segments, ConstantGroup $group): bool
    {
        if ($segments === []) {
            if (isset($node[$group->name()])) {
                return false;
            }

            $node[$group->name()] = $group;

            return true;
        }

        $segment = array_shift($segments);
        $child = $node[$segment] ?? [];

        if (! is_array($child)) {
            return false;
        }

        if (! self::place($child, $segments, $group)) {
            return false;
        }

        $node[$segment] = $child;

        return true;
    }

    private function renderNode(mixed $node, int $depth): string
    {
        if ($node instanceof ConstantGroup) {
            return TypeScript::object(array_map(
                fn (mixed $value): string => $this->renderValue($value, $depth + 1) ?? 'undefined',
                $node->constants()
            ), $depth);
        }

        return TypeScript::object(array_map(
            fn (mixed $child): string => $this->renderNode($child, $depth + 1),
            is_array($node) ? $node : []
        ), $depth);
    }

    /**
     * Render a PHP value as TypeScript, or null when it has no representation.
     */
    private function renderValue(mixed $value, int $depth): ?string
    {
        return match (true) {
            $value === null => 'null',
            is_bool($value) => $value ? 'true' : 'false',
            is_int($value) => (string) $value,
            is_float($value) => is_finite($value) ? var_export($value, true) : null,
            is_string($value) => TypeScript::string($value),
            $value instanceof BackedEnum => $this->renderValue($value->value, $depth),
            $value instanceof UnitEnum => TypeScript::string($value->name),
            $value instanceof JsonSerializable => $this->renderSerialized($value->jsonSerialize(), $depth),
            is_array($value) => $this->renderArray($value, $depth),
            default => null,
        };
    }

    private function renderSerialized(mixed $serialized, int $depth): ?string
    {
        return $serialized instanceof JsonSerializable ? null : $this->renderValue($serialized, $depth);
    }

    /**
     * @param  array<mixed>  $value
     */
    private function renderArray(array $value, int $depth): ?string
    {
        $rendered = [];

        foreach ($value as $key => $item) {
            $itemValue = $this->renderValue($item, $depth + 1);

            if ($itemValue === null) {
                return null;
            }

            $rendered[$key] = $itemValue;
        }

        return array_is_list($rendered)
            ? TypeScript::array($rendered, $depth)
            : TypeScript::object($rendered, $depth);
    }

    /**
     * One exported union type per group, named after the group. Names that would
     * collide — with another group or with a top-level constant object — take in
     * enclosing namespace segments until they are unique.
     *
     * @param  list<ConstantGroup>  $groups
     * @param  list<string>  $reserved
     * @return list<string>
     */
    private function typeAliases(array $groups, array $reserved): array
    {
        $taken = array_fill_keys($reserved, true);
        $aliases = [];

        foreach ($groups as $group) {
            $name = $this->uniqueTypeName($group, $taken);
            $taken[$name] = true;
            $path = $group->path();

            $aliases[] = "export type {$name} = (typeof {$path})[keyof typeof {$path}];";
        }

        return $aliases;
    }

    /**
     * @param  array<string, true>  $taken
     */
    private function uniqueTypeName(ConstantGroup $group, array $taken): string
    {
        $segments = $group->namespace();
        $name = $group->name();

        while (isset($taken[$name]) && $segments !== []) {
            $name = array_pop($segments).$name;
        }

        $candidate = $name;
        $suffix = 2;

        while (isset($taken[$candidate])) {
            $candidate = $name.$suffix++;
        }

        return $candidate;
    }
}
